Enable tap-to-click pref in macOS

diff --git a/run_onchange_mac-settings.zsh.tmpl b/run_onchange_mac-settings.zsh.tmpl
--- a/run_onchange_mac-settings.zsh.tmpl
+++ b/run_onchange_mac-settings.zsh.tmpl
@@ -1,5 +1,25 @@
 #!/bin/zsh
 
+# This script will run (if there's a change) during `chezmoi apply`.
+
+echo
+echo "👋 Running on-change script for macOS settings..."
+
 {{/* This makes the script run after each macOS update. */}}
 # MacOS build version: {{ output "sw_vers" "--buildVersion" }}
-echo "Please work!!"
+
+echo "Setting macOS preference to enabled tap-to-click on built-in touchpad..."
+defaults write com.apple.driver.AppleMultitouchTrackpad Clicking -bool true
+if [[ $? -ne 0 ]]; then
+  echo
+  echo "☠️ Error settting macOS preference. Please check the output above."
+  exit 1
+fi
+
+echo "Killing cfprefsd to reload cached preferences (the cfprefsd process should restart)..."
+killall cfprefsd
+if [[ $? -ne 0 ]]; then
+  echo
+  echo "☠️ Error killing cfprefsd process. Please check the output above."
+  exit 1
+fi
