Try something else for tap-to-click

diff --git a/run_onchange_mac-settings.zsh.tmpl b/run_onchange_mac-settings.zsh.tmpl
--- a/run_onchange_mac-settings.zsh.tmpl
+++ b/run_onchange_mac-settings.zsh.tmpl
@@ -8,18 +8,19 @@ echo "👋 Running on-change script for macOS settings..."
 {{/* This makes the script run after each macOS update. */}}
 # MacOS build version: {{ output "sw_vers" "--buildVersion" }}
 
-echo "Setting macOS preference to enabled tap-to-click on built-in touchpad..."
-defaults write com.apple.driver.AppleMultitouchTrackpad Clicking -bool true
+echo "Setting macOS preference to enabled tap-to-click on built-in trackpad..."
+defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
 if [[ $? -ne 0 ]]; then
   echo
   echo "☠️ Error settting macOS preference. Please check the output above."
   exit 1
 fi
 
-echo "Killing cfprefsd to reload cached preferences (the cfprefsd process should restart)..."
-killall cfprefsd
-if [[ $? -ne 0 ]]; then
-  echo
-  echo "☠️ Error killing cfprefsd process. Please check the output above."
-  exit 1
-fi
+# This doesn't seem to do anything.
+# echo "Killing cfprefsd to reload cached preferences (the cfprefsd process should restart)..."
+# killall cfprefsd
+# if [[ $? -ne 0 ]]; then
+#   echo
+#   echo "☠️ Error killing cfprefsd process. Please check the output above."
+#   exit 1
+# fi
